# -*- coding: utf-8 -*-
"""EMS _assesment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lNM-g-mFLwv_0HJdTyLSJGABN8OpGxOD
"""

#Objective - Create a simplified Employee Management System (EMS). This project will cover control structures, functions,
# and object-oriented programming concepts to manage employee data.

'''Use a dictionary to store employee data where the keys is the emp_id (Employee ID) and the value is another dictionary containing:


name: Employee's name.
age: Employee's age.
department: Employee's department.
salary: Employee's monthly salary.
'''

"""**# Step 1 - Data Storage (Pre-filled sample data)**"""

employees = {
    101: {"name": "Satya", "age": 27, "department": "HR", "salary": 50000},
    102: {"name": "Rohan", "age": 30, "department": "IT", "salary": 65000}
}

"""**Menu system**"""

def main_menu():
    print("Employee Management System")
    print("1. Add Employee")
    print("2. View Employee")
    print("3. Update Employee")
    print("4. Delete Employee")
    print("5. Exit")
    choice = input("Enter your choice: ")
    if choice == "1":
      add_employee()
    elif choice == "2":
      view_employees() # Corrected function call
    elif choice == "3":
      update_employee()
    elif choice == "4":
      delete_employee()
    elif choice == "5":
      print('Thanks for working with as !')
      exit()
    else:
      print("Invalid choice. Please try again.")
      main_menu()

"""**# Step 3 - Add Employee Functionality**"""

def add_employee():
    try:
        emp_id = int(input("Enter Employee ID: "))

        if emp_id in employees:
            print("Employee ID already exists. Please enter a unique ID.")
            return

        name = input("Enter Employee Name: ")
        age = int(input("Enter Employee Age: "))
        department = input("Enter Employee Department: ")
        salary = float(input("Enter Employee Salary: "))

        employees[emp_id] = {
            "name": name,
            "age": age,
            "department": department,
            "salary": salary
        }

        print("Employee added successfully!")

    except ValueError:
        print("Invalid input. Please enter correct values.")

# Step 4 - View All Employees
def view_employees():
    if not employees:
        print("No employees available.")
        return

    print("\n===== Employee List =====")
    print("ID\tName\tAge\tDepartment\tSalary")
    print("-----------------------------------------------")

    for emp_id, details in employees.items():
        print(f"{emp_id}\t{details['name']}\t{details['age']}\t{details['department']}\t\t{details['salary']}")

# Step 5 - Search for Employee by ID
def search_employee():
    try:
        emp_id = int(input("Enter Employee ID to search: "))

        if emp_id in employees:
            emp = employees[emp_id]
            print("\nEmployee Found:")
            print(f"ID: {emp_id}")
            print(f"Name: {emp['name']}")
            print(f"Age: {emp['age']}")
            print(f"Department: {emp['department']}")
            print(f"Salary: {emp['salary']}")
        else:
            print("Employee not found.")

    except ValueError:
        print("Invalid input. Please enter a valid ID.")

# Step 6 - Run the Program
main_menu()

